name       : python-numexpr
version    : 2.6.4
release    : 3
source     :
    - https://github.com/pydata/numexpr/archive/v2.6.4.tar.gz : 049da1c07bd62d2aba29887130ccc9aff9b90962cb779a7b7ddc15e580368fba
license    : MIT
component  : programming.python
summary    : Fast numerical array expression evaluator for Python, NumPy, PyTables,
    pandas, bcolz and more.
description: |
    Fast numerical array expression evaluator for Python, NumPy, PyTables, pandas, bcolz and more.
builddeps  :
    - pkgconfig(python3)
    - numpy
    - python-setuptools
rundeps    :
    - numpy
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
