name       : python-numexpr
version    : 2.7.1
release    : 7
source     :
    - https://github.com/pydata/numexpr/archive/v2.7.1.tar.gz : 5c6ae3bb5688184b922b43fc47de49d642576d0feec55a1b679caa66efae90a1
license    : MIT
component  : programming.python
summary    : Fast numerical array expression evaluator for Python, NumPy, PyTables, pandas, bcolz and more
description: |
    Fast numerical array expression evaluator for Python, NumPy, PyTables, pandas, bcolz and more.
builddeps  :
    - pkgconfig(python3)
    - numpy
rundeps    :
    - numpy
build      : |
    %python3_setup
install    : |
    %python3_install
