name       : python-numexpr
version    : 2.8.3
release    : 13
source     :
    - https://github.com/pydata/numexpr/archive/refs/tags/v2.8.3.tar.gz : 389ceefca74eff30ec3fd03fc4c3b7ab3df8f22d1f235117a392ce702ed208c0
homepage   : https://github.com/pydata/numexpr
license    : MIT
component  : programming.python
summary    : Fast numerical array expression evaluator for Python, NumPy, PyTables, pandas, bcolz and more
description: |
    NumExpr is a fast numerical expression evaluator for NumPy. With it, expressions that operate on arrays (like '3*a+4*b') are accelerated and use less memory than doing the same calculation in Python.
builddeps  :
    - pkgconfig(python3)
    - numpy
    - python-packaging  # check
rundeps    :
    - numpy
    - python-packaging
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
